name: scppg_example
description: An example for using the scppg package.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.1
  permission_handler: ^12.0.0
  get_it: ^8.0.3
  syncfusion_flutter_charts: ^29.2.4
  scppg: 
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.24.0