name: scppg
description: A Flutter package for smartphone camera photoplethysmography (SCPPG) that enables heart rate monitoring using smartphone cameras. Provides a controller to handle camera initialization, permission management, RGB extraction from camera frames, and finger detection, making it easy to implement heart rate monitoring features in health and wellness applications.
version: 1.0.0
homepage: https://github.com/dcajal/scppg
repository: https://github.com/dcajal/scppg

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.1
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  mocktail: ^1.0.3