name: scppg
description: A Flutter package for smartphone camera photoplethysmography (SCPPG) that enables heart rate monitoring using smartphone cameras.
version: 1.2.1
homepage: https://github.com/dcajal/scppg
repository: https://github.com/dcajal/scppg

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.1
  permission_handler: ^12.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  mocktail: ^1.0.3